excluded:
  - .build
  - .git

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 75
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 20

line_length:
  warning: 150
  error: 200

disabled_rules:
  - trailing_comma
  - vertical_parameter_alignment_on_call
  - force_cast
  - force_try
