import Foundation

#if canImport(SwiftUI)
import SwiftUI
#endif

/// A color in linear sRGB space with floating-point components [0, 1].
///
/// Use this type to work with colors generated by ColorJourney or to specify
/// anchor colors for journeys. Easily convert to platform-specific formats like
/// `Color` (SwiftUI), `UIColor` (iOS), or `NSColor` (macOS).
///
/// ## Initialization
///
/// ```swift
/// let red = ColorJourneyRGB(red: 1.0, green: 0.0, blue: 0.0)
/// let blue = ColorJourneyRGB(red: 0.0, green: 0.0, blue: 1.0)
/// ```
///
/// ## Platform Conversion
///
/// ```swift
/// let swiftUIColor = color.color           // SwiftUI Color
/// let uiColor = color.uiColor              // UIKit (iOS/iPadOS)
/// let nsColor = color.nsColor              // AppKit (macOS)
/// ```
public struct ColorJourneyRGB: Hashable {
    /// Red component [0, 1]
    public var red: Float
    /// Green component [0, 1]
    public var green: Float
    /// Blue component [0, 1]
    public var blue: Float

    /// Create a color with RGB components.
    ///
    /// - Parameters:
    ///   - red: Red channel [0, 1]
    ///   - green: Green channel [0, 1]
    ///   - blue: Blue channel [0, 1]
    public init(red: Float, green: Float, blue: Float) {
        self.red = red
        self.green = green
        self.blue = blue
    }

    #if canImport(SwiftUI)
    /// SwiftUI `Color` representation.
    ///
    /// Use this property to apply the color in SwiftUI views:
    /// ```swift
    /// Rectangle().fill(color.color)
    /// ```
    public var color: Color {
        Color(red: Double(red), green: Double(green), blue: Double(blue))
    }
    #endif

    #if canImport(AppKit)
    /// AppKit `NSColor` representation (macOS).
    public var nsColor: NSColor {
        NSColor(red: CGFloat(red), green: CGFloat(green), blue: CGFloat(blue), alpha: 1.0)
    }
    #endif

    #if canImport(UIKit)
    /// UIKit `UIColor` representation (iOS/iPadOS).
    public var uiColor: UIColor {
        UIColor(red: CGFloat(red), green: CGFloat(green), blue: CGFloat(blue), alpha: 1.0)
    }
    #endif
}

#if canImport(SwiftUI)
extension Color {
    /// Initialize from a `ColorJourneyRGB`.
    ///
    /// ```swift
    /// let swiftColor = Color(journeyRGB: journeyColor)
    /// ```
    public init(journeyRGB: ColorJourneyRGB) {
        self = journeyRGB.color
    }
}
#endif
